createOrReplace

	/// Container voor metingen. 
	table Metingen
		lineageTag: 1dcdc921-5c58-4bac-b5bc-0ddb3c2a7b55

		/// Dummy measure voor metingen in tabel.
		/// 
		measure 'Dummy Meting' = 0
			formatString: 0
			lineageTag: 8d2c6a42-db55-41cf-b9af-4eb94adea99c

		partition Metingen = m
			mode: import
			source =
					let
					    Bron = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Kolom 1" = _t]),
					    #"Type gewijzigd" = Table.TransformColumnTypes(Bron,{{"Kolom 1", type text}}),
					    #"Kolommen verwijderd" = Table.RemoveColumns(#"Type gewijzigd",{"Kolom 1"})
					in
					    #"Kolommen verwijderd"

		annotation PBI_ResultType = Table

