table 'Slaapdata (G)'
	lineageTag: 3cf8df98-5e32-41c1-adf8-be72ec171d84

	column datum
		dataType: dateTime
		formatString: Long Date
		isHidden
		displayFolder: _Verborgen
		lineageTag: ec9354c2-3f72-418e-a821-8139184bbac5
		summarizeBy: none
		sourceColumn: datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column slaap_start
		dataType: dateTime
		formatString: General Date
		isHidden
		displayFolder: _Verborgen
		lineageTag: 14547b89-097c-48b9-9888-90d2a3b0055b
		summarizeBy: none
		sourceColumn: slaap_start

		annotation SummarizationSetBy = Automatic

	column slaap_einde
		dataType: dateTime
		formatString: General Date
		isHidden
		displayFolder: _Verborgen
		lineageTag: 2feb2193-179d-4184-b891-8f71c59ed544
		summarizeBy: none
		sourceColumn: slaap_einde

		annotation SummarizationSetBy = Automatic

	column totale_slaap_uur
		dataType: double
		formatString: 0.0
		isHidden
		displayFolder: _Verborgen
		lineageTag: b80e6c9e-5b9d-4e9b-9584-20f19b24cb85
		summarizeBy: sum
		sourceColumn: totale_slaap_uur

		annotation SummarizationSetBy = Automatic

	column diepe_slaap_uur
		dataType: double
		formatString: 0.0
		isHidden
		displayFolder: _Verborgen
		lineageTag: 045387a3-ba98-40e2-a488-1f915aa0be38
		summarizeBy: sum
		sourceColumn: diepe_slaap_uur

		annotation SummarizationSetBy = Automatic

	column lichte_slaap_uur
		dataType: double
		formatString: 0.0
		isHidden
		displayFolder: _Verborgen
		lineageTag: a2c318a1-2393-4be9-8e02-6b04842e2120
		summarizeBy: sum
		sourceColumn: lichte_slaap_uur

		annotation SummarizationSetBy = Automatic

	column rem_slaap_uur
		dataType: double
		formatString: 0.0
		isHidden
		displayFolder: _Verborgen
		lineageTag: 64988f69-d521-4a99-a2d0-db8c4793a42d
		summarizeBy: sum
		sourceColumn: rem_slaap_uur

		annotation SummarizationSetBy = Automatic

	column wakker_uur
		dataType: double
		formatString: 0.0
		isHidden
		displayFolder: _Verborgen
		lineageTag: 0473c198-8950-49ee-9db7-db51dde0859c
		summarizeBy: sum
		sourceColumn: wakker_uur

		annotation SummarizationSetBy = Automatic

	column slaapscore
		dataType: int64
		formatString: 0
		isHidden
		displayFolder: _Verborgen
		lineageTag: a6341fd0-537b-4739-a14c-e4f6a8b0442a
		summarizeBy: sum
		sourceColumn: slaapscore

		annotation SummarizationSetBy = Automatic

	column slaapscore_kwalificatie
		dataType: string
		lineageTag: 1c2e5d7d-fd04-42d1-908e-4f3803180004
		summarizeBy: none
		sourceColumn: slaapscore_kwalificatie

		annotation SummarizationSetBy = Automatic

	column gemiddelde_ademhaling
		dataType: double
		formatString: 0.0
		isHidden
		displayFolder: _Verborgen
		lineageTag: afc75bd2-4c24-4f75-86f8-1582373c85bf
		summarizeBy: sum
		sourceColumn: gemiddelde_ademhaling

		annotation SummarizationSetBy = Automatic

	column gemiddelde_hartslag_in_slaap
		dataType: int64
		formatString: 0
		isHidden
		displayFolder: _Verborgen
		lineageTag: 168358d1-2c1a-490a-a84b-2d85b8e2d203
		summarizeBy: sum
		sourceColumn: gemiddelde_hartslag_in_slaap

		annotation SummarizationSetBy = Automatic

	column gemiddelde_hrv
		dataType: double
		formatString: 0
		isHidden
		displayFolder: _Verborgen
		lineageTag: af52601f-3c7d-40d8-a9d2-597811adb62a
		summarizeBy: none
		sourceColumn: gemiddelde_hrv

		annotation SummarizationSetBy = Automatic

	column aantal_ontwakingen
		dataType: string
		lineageTag: cade319c-c016-48cc-8aa9-3643f94583a6
		summarizeBy: none
		sourceColumn: aantal_ontwakingen

		annotation SummarizationSetBy = Automatic

	column onrustige_momenten
		dataType: string
		lineageTag: 7ebf6cee-8c8b-440e-982e-ca447d717c18
		summarizeBy: none
		sourceColumn: onrustige_momenten

		annotation SummarizationSetBy = Automatic

	column gem_slaapstress
		dataType: string
		lineageTag: 61698504-e241-43dd-99f6-002adedd0439
		summarizeBy: none
		sourceColumn: gem_slaapstress

		annotation SummarizationSetBy = Automatic

	column bb_start
		dataType: string
		lineageTag: 0daf79b6-7964-430b-9f0f-1b5d6581f49b
		summarizeBy: none
		sourceColumn: bb_start

		annotation SummarizationSetBy = Automatic

	column bb_einde
		dataType: string
		lineageTag: e814bd9a-bb1a-40a7-a1fc-43f618f15a5c
		summarizeBy: none
		sourceColumn: bb_einde

		annotation SummarizationSetBy = Automatic

	column bb_laagste
		dataType: string
		lineageTag: 19e89a56-c44a-4b3f-814c-f93d1569111b
		summarizeBy: none
		sourceColumn: bb_laagste

		annotation SummarizationSetBy = Automatic

	column bb_hoogste
		dataType: string
		lineageTag: efee0f13-f0d0-401e-ab2c-77e65330fc91
		summarizeBy: none
		sourceColumn: bb_hoogste

		annotation SummarizationSetBy = Automatic

	column bb_verandering
		dataType: string
		lineageTag: 64129305-9bd4-4f7f-9dd6-c70891ffbc9c
		summarizeBy: none
		sourceColumn: bb_verandering

		annotation SummarizationSetBy = Automatic

	column spo2_gem_trend
		dataType: string
		lineageTag: 16f19598-4caf-40cc-a06a-51eeef180bb8
		summarizeBy: none
		sourceColumn: spo2_gem_trend

		annotation SummarizationSetBy = Automatic

	column spo2_laagste_trend
		dataType: string
		lineageTag: 994cb387-bbf5-4fca-9f55-8b31229183d1
		summarizeBy: none
		sourceColumn: spo2_laagste_trend

		annotation SummarizationSetBy = Automatic

	column spo2_hoogste_trend
		dataType: string
		lineageTag: f34527a7-5169-49b6-aa48-3180f04606cd
		summarizeBy: none
		sourceColumn: spo2_hoogste_trend

		annotation SummarizationSetBy = Automatic

	partition 'Slaapdata (G)' = m
		mode: import
		queryGroup: FACT\Garmin
		source =
				let
				    Bron = #"Garmin Bron",
				    Content = Bron{1}[Content],
				    #"CSV-bestand geïmporteerd" = Csv.Document(Content,[Delimiter=",", Columns=24, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Headers met verhoogd niveau" = Table.PromoteHeaders(#"CSV-bestand geïmporteerd", [PromoteAllScalars=true]),
				    #"Type gewijzigd" = Table.TransformColumnTypes(#"Headers met verhoogd niveau",{{"datum", type date}, {"slaap_start", type datetime}, {"slaap_einde", type datetime}, {"slaapscore_kwalificatie", type text}, {"aantal_ontwakingen", type text}, {"onrustige_momenten", type text}, {"gem_slaapstress", type text}, {"bb_start", type text}, {"bb_einde", type text}, {"bb_laagste", type text}, {"bb_hoogste", type text}, {"bb_verandering", type text}, {"spo2_gem_trend", type text}, {"spo2_laagste_trend", type text}, {"spo2_hoogste_trend", type text}}),
				    // Lege strings naar null zodat numerieke conversie niet faalt op ontbrekende waarden
				    #"Lege waarden" = Table.ReplaceValue(#"Type gewijzigd", "", null, Replacer.ReplaceValue, {"totale_slaap_uur", "diepe_slaap_uur", "lichte_slaap_uur", "rem_slaap_uur", "wakker_uur", "slaapscore", "gemiddelde_ademhaling", "gemiddelde_hartslag_in_slaap", "gemiddelde_hrv"}),
				    // Python-export gebruikt punt als decimaalteken → en-US conversie
				    #"Numeriek en-US" = Table.TransformColumnTypes(#"Lege waarden", {{"totale_slaap_uur", type number}, {"diepe_slaap_uur", type number}, {"lichte_slaap_uur", type number}, {"rem_slaap_uur", type number}, {"wakker_uur", type number}, {"gemiddelde_ademhaling", type number}, {"gemiddelde_hrv", type number}, {"slaapscore", type number}, {"gemiddelde_hartslag_in_slaap", type number}}, "en-US"),
				    // Scores en hartslag zijn gehele getallen
				    #"Gehele getallen" = Table.TransformColumnTypes(#"Numeriek en-US",{{"slaapscore", Int64.Type}, {"gemiddelde_hartslag_in_slaap", Int64.Type}})
				in
				    #"Gehele getallen"

	annotation PBI_NavigationStepName = Navigatie

	annotation PBI_ResultType = Table

